// Automatically generated by astro-icon
// 77e150351ba1d8e919b00ac34b13c06a638208126eab761084f35c1dd7e48bc5

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "bars"
		| "github"
		| "linkedin"
		| "xmark";
}